# Generated by Django 3.2.4 on 2021-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='last_date_update',
            field=models.DateTimeField(verbose_name='Last date update'),
        ),
    ]
