# Generated by Django 3.2.4 on 2021-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_last_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='last_date_info',
            field=models.DateTimeField(auto_now=True, verbose_name='Last date info'),
        ),
    ]
